name: Auto Merge

on:
  push:
    branches:
      - pre-production

env:
  MY_REPO: https://sonali-makerble:${{secrets.GITHUB_TOKEN}}@github.com/sonali-makerble/auto-merge-to-develop.git
  MY_BRANCH: develop
  MASTER_REPO: https://sonali-makerble:${{secrets.GITHUB_TOKEN}}@github.com/sonali-makerble/auto-merge-to-develop.git
  MASTER_BRANCH: pre-production

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ${{env.MASTER_BRANCH}}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create new branch
      run: |
        git config user.name "Automerge Bot"
        git config user.email "bot@example.com"
        git checkout -b merge-${{env.MASTER_BRANCH}}-to-${{env.MY_BRANCH}}
        git push ${{env.MY_REPO}} HEAD:${{env.MY_BRANCH}}-update

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update report
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: example-patches
        delete-branch: true
        title: '[Example] Update report'
        body: "This PR is automatically created to merge changes from ${MASTER_BRANCH} into ${MY_BRANCH}."
