name: Auto Merge

on:
  push:
    branches:
      - pre-production

env:
  MY_REPO: https://sonali-makerble:${{secrets.GITHUB_TOKEN}}@github.com/sonali-makerble/auto-merge-to-develop.git
  TO_BRANCH: develop
  MASTER_REPO: https://sonali-makerble:${{secrets.GITHUB_TOKEN}}@github.com/sonali-makerble/auto-merge-to-develop.git
  FROM_BRANCH: pre-production

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ${{env.MASTER_BRANCH}}
        token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Merge pre-production into develop
    #   run: |
    #     git clone ${{env.MASTER_REPO}} -b ${{env.TO_BRANCH}} tmp
    #     cd tmp
    #     git config user.name "Automerge Bot"
    #     git config user.email "automergebot@makerble.com"
    #     git config pull.rebase false
    #     git pull ${{env.MASTER_REPO}} ${{env.FROM_BRANCH}}
    #     git push origin ${{env.TO_BRANCH}}

    - name: Create new branch
      run: |
        git config user.name "Automerge Bot"
        git config user.email "bot@example.com"
        git checkout -b merge-${{env.FROM_BRANCH}}-to-${{env.TO_BRANCH}}
        git push origin merge-${{env.FROM_BRANCH}}-to-${{env.TO_BRANCH}}

    - name: Raise PR
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        branch:  ${{env.TO_BRANCH}}
        base: merge-${{env.FROM_BRANCH}}-to-${{env.TO_BRANCH}}
        title: "demo for auto pr1"
        committer: sonali <sonali123@gmail.com>
        author: sonali <sonali123@gmail.com>
        body:
          This is to show automatic PR creation
        token: ${{ secrets.GITHUB_TOKEN }}
      
