name: Auto Merge

on:
  push:
    branches:
      - pre-production

env:
  MY_REPO: https://sonali-makerble:${{secrets.GITHUB_TOKEN}}@github.com/sonali-makerble/auto-merge-to-develop.git
  TO_BRANCH: develop
  MASTER_REPO: https://sonali-makerble:${{secrets.GITHUB_TOKEN}}@github.com/sonali-makerble/auto-merge-to-develop.git
  FROM_BRANCH: pre-production

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ${{env.MASTER_BRANCH}}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Merge pre-production into develop
      run: |
        git clone ${{env.MASTER_REPO}} -b ${{env.TO_BRANCH}} tmp
        cd tmp
        git config user.name "Automerge Bot"
        git config user.email "automergebot@makerble.com"
        git config pull.rebase false
        git pull ${{env.MASTER_REPO}} ${{env.FROM_BRANCH}}
        git push origin ${{env.TO_BRANCH}}
    - name: Setup GitHub CLI
      run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
    - name: Create Pull Request
      run: gh pr create -B ${{env.TO_BRANCH}} -H ${{ github.ref_name }} --title 'Auto-generated Pull Request' --body 'This PR is auto-generated by GitHub Actions.'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: Create Pull Request
    #   uses: actions/github-script@v6
    #   with:
    #     script: |
    #       const { repo, owner } = context.repo;
    #       const result = await github.rest.pulls.create({
    #         title: 'Auto-generated Pull Request',
    #         owner,
    #         repo,
    #         head: '${{ github.ref_name }}',
    #         base: ${{env.TO_BRANCH}}
    #         body: 'This PR is auto-generated by GitHub Actions.',
    #       });
    #       github.rest.issues.addLabels({
    #         owner,
    #         repo,
    #         issue_number: result.data.number,
    #         labels: ['automated pr']
    #       });
      
