name: Generate Sitemap

on:
  push:
    branches:
      - main

env:
  TO_BRANCH: main
  FROM_BRANCH: sitemap-update

jobs:
  generate_sitemap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Create new branch
      run: |
        git checkout -b sitemap-update
        git config --global user.email "github-action@example.com"
        git config --global user.name "GitHub Action"

    - name: Install sitemap-generator-cli
      run: npm install -g sitemap-generator-cli

    - name: Generate sitemap
      run: sitemap-generator https://www.google.com

    - name: Move sitemap.xml to public directory
      run: mv sitemap.xml public/

    - name: Commit and push changes
      run: |
        git add public/sitemap.xml
        git commit -m "Updated sitemap.xml"
        git push --set-upstream origin sitemap-update

    - name: Setup GitHub CLI
      run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

    - name: Install jq
      run: sudo apt-get install jq

    - name: Create Pull Request
      run: |
        PR_JSON=$(gh api repos/${{ github.repository }}/pulls?base=${{ env.TO_BRANCH }}\&head=${{ env.FROM_BRANCH }})
        PR_EXISTS=$(echo "$PR_JSON" | jq '[.[] | select(.base.ref == $to_branch and .head.ref == $from_branch)] | length > 0' --arg to_branch "${{ env.TO_BRANCH }}" --arg from_branch "${{ env.FROM_BRANCH }}")
        if [ "$PR_EXISTS" != "true" ]; then
          gh pr create -B ${{ env.TO_BRANCH }} -H ${{ env.FROM_BRANCH }} --reviewer mukul-kr --title 'Auto-generated Pull Request' --body 'This PR is auto-generated by GitHub Actions.'
        fi
        PR_NUMBER=$(gh api repos/${{ github.repository }}/pulls | jq -r --arg head_ref ${{ env.FROM_BRANCH }} --arg base_ref ${{ env.TO_BRANCH }} '.[] | select(.head.ref == $head_ref and .base.ref == $base_ref) | .number')
        echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
        echo $PR_NUMBER
      id: create_pull_request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Approve Pull Request
      uses: juliangruber/approve-pull-request-action@v2.0.0
      with:
        github-token: ${{ secrets.OTHER_TOKEN }}
        number: ${{ env.PR_NUMBER }}

    - name: Merge Pull request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.OTHER_TOKEN }}
        number: ${{ env.PR_NUMBER }}
        method: merge